### ISSUE TITLE
Surface custom errors from subtypes?

### ISSUE THREAD

**Issue by eviltoylet** [gcanti/tcomb-validation#9]
Are there any plans to allow custom validation errors on a subtype? I've got the following subtype:
```
t.subtype(t.Str, function (string) {
	try {
		JSON.parse(string);
		return true;
	} catch (e) {
		// surface e.message?
		return false;
	}
}, "JSON Schema");
```

**Comment by gcanti** [comment]
Hi, 
I have the plan to merge tcomb, tcomb-validation and [flowcheck](https://github.com/gcanti/flowcheck) (`assert.js`) libraries in tcomb v2.0. In particular the way flowcheck represents the sets (with a `validate` function instead of a predicate) will allow custom error messages for user defined types.
